### ISSUE TITLE
Rendre la phase de relâchement du ballon (BAVU) plus fiable

### ISSUE THREAD

**Issue by arnaud-clere** [Recovid/Controller#38]
Le ballon est comprimé par une cordelette kevlar relativement rigide qui bien que tenue sur les poulies par des tours morts et des caches pourrait se détendre trop et s'enrouler provoquant une défaillance irrémédiable du cycle respiratoire (un arrêt et une remise en place par des personnes qualifiées étant nécessaire pour réparer le recovid). La commande de relâchement moteur semble actuellement trop brusque pour éliminer ce risque. 

Aussi, en cas d'alarme Pmax, passer bursquement d'une commande moteur guidée par DMA+PWM à une commande relâchement (PWM constant ?) inverse à haute vitesse risque peut-être de mettre le moteur en difficulté (mode de défaillance ?)

L'idéal serait de toujours demander au moteur+mécanique de faire un cycle régulier, la sécurité patient étant en fait assurée exclusivement par l'éléctrovanne PEP (descente de pression en - de 200ms).

On peut déjà introduire une temporisation entre commandes press/release dans le cycle respiration, par ex. ne faire le release que dans Exhalation après 100ms.
Ensuite, on pourrait programmer un mouvement release en DMA avec une table de "step_t_us" avec accélération/décélération progressive.

**Comment by arnaud-clere** [comment]
Pour Cyril, on ne pourra pas ne pas arrêter la compression du ballon dès le VTi observé atteint car ça risque de perturber le circuit pneumatique. Siméon discute avec ST pour avoir un arrêt propre du pilotage du mouvement de compression en DMA+PWM.

**Comment by simson** [comment]
Fixed by bf218268cc2491dcad23ccb92acb369803d18d84
