### ISSUE TITLE
Timer de manière précise les acquisitions des capteurs I2C pression et flux

### ISSUE THREAD

**Issue by arnaud-clere** [Recovid/Controller#44]
Les données sont envoyées par les capteurs I2C (NPA et SDP) à leur rythme, à priori bien plus élevé que la fréquence théorique de 1kHz et 200Hz. 

Il faut déterminer si les valeurs supplémentaires sont des doublons. 

Si non, il faudrait d'une part pouvoir déterminer leur intervalle plus précisément qu'à la ms actuelle pour gagner en précision sur l'intégration du volume.

Et aussi les moyenner car il n'est pas évident qu'on puisse stocker beaucoup plus que les 200 échantillons actuels capturés à au moins 2ms d'intervalle pendant l'insufflation.

La branche freertos_periodic_timer peut être utilisée pour traiter ce problème en planifiant une tâche FreeRTOS à 1kHz. Par ailleurs, certaines branches de Controller-V1-F303 prennent un timer en µs en utilisant TIM_HandleTypeDef.

**Comment by arnaud-clere** [comment]
intervalles sampling capteurs calculés par siméon avec timer µs : 4,8... pour Pdiff, 1,... pour Paw

**Comment by JulienDevillers** [comment]
Après étude du fonctionnement des capteurs, nous avons conclu avec Siméon que le fonctionnement actuel est le plus efficace. Inclure tout de même la pull request que j'ai faite sur I2C.
Etant donné que le capteur ne signifie pas qu'il a de la donnée, le moyen d'avoir de la donnée fraîche est de l'interroger le plus souvent possible.
